### ISSUE TITLE
Frontend: screen to show all errors and warnings

### ISSUE THREAD

**Issue by praseodym** [kiesraad/abacus#103]
Add check screen according to [Figma section "Controleren en opslaan"](https://www.figma.com/design/zZlFr8tYiRyp4I26sh6eqp/Kiesraad---Abacus-optelsoftware?node-id=3725-15701&node-type=SECTION&t=Jo48EtFi2NgcMsKe-11).

Business logic:
- when there are no errors and no not accepted warnings:
  - first item in list is 'Alle optellingen kloppen'
  - last two item in list are 'Er zijn geen blokkerende fouten of waarschuwingen' and 'Je kan de resultaten van dit stembureau opslaan'
- when there are no errors but there are not accepted warnings:
  - First item in list is 'Alle optellingen kloppen'
  - Last item in list is 'Je kan de resultaten van dit stembureau nog niet opslaan'
  - there is no submit button.
- when there are errors:
  -  Last item in list is 'Je kan de resultaten van dit stembureau nog niet opslaan'
  - there is no submit button
 
between the list items mentioned above, we loop through all pages/sections of the form and we
- do not show items that don't have warnings or errors
- if an item contains no/all 0 input we show 'Bij `<step>` zijn geen aantallen ingevoerd'
- if an item contains accepted warnings: '`<step>` heeft geaccepteerde waarschuwingen'
- if an item contains not accepted warnings: 'Controleer waarschuwingen bij `<step>`'
- if an item contains errors: '`<step>` heeft blokkerende fouten' 

`<step>` is a link to the section that contains the error/warning. The link texts is the name of the step as used in the navigation menu, except for political groups. There we only use 'Lijst `<listnumber>`', we leave out the name of the political group

**Comment by praseodym** [comment]
@jorisleker is going to re-check the design for this.

**Comment by jorisleker** [comment]
Done. Updated design and description of the ticket

**Comment by lkleuver** [comment]
Should we perhaps have a slight visual difference in a "list item" that is blocking "saving". Like unaccepted warnings.

**Comment by jorisleker** [comment]
> Should we perhaps have a slight visual difference in a "list item" that is blocking "saving". Like unaccepted warnings.

This crossed my mind too. 'Fix' could be to differentiate between accepted and unaccepted warnings. My idea suggestion be to update _accepted_ warnings to the green checkmark, and only use the triangle+exclamation mark for unaccepted warnings. Line of thought would be that an accepted/checked warning isn't really a warning anymore.

But: if we do this, we should also update the way we use these icons in the navigation menu. Might be too big a change to implement in this PR, better to make this into a separate issue?

**Comment by praseodym** [comment]
Can you navigate to "controleren en opslaan" with unaccepted warnings?

**Comment by jorisleker** [comment]
> Can you navigate to "controleren en opslaan" with unaccepted warnings?

Yes, you can like this:

- Fill out everything and accept any warning
- You can reach "controleren en opslaan". 
- Now, navigate to a previous section
- Make changes that will trigger a warning
- Click "Volgende"
- You remain on the 'current page' with the accept warnings checkbox unchecked. 
- Use the navigation to navigate to "controleren en opslaan".

**Comment by lkleuver** [comment]
My initial thought was to split the list in 2 lists with headers, blockers and summary

**Comment by lkleuver** [comment]
@jorisleker Is there a design for this?
"The check screen should show all errors and warnings, even if an error or warning in the API response refers to fields that are not known to the frontend (so no filtering of errors or warnings)."

**Comment by jorisleker** [comment]
@lkleuver updated the description of the issue, with link to updated design
