### ISSUE TITLE
Epic: status on polling station choice page

### ISSUE THREAD

**Issue by praseodym** [kiesraad/abacus#131]
Expand the polling station choice page with status of data entry.

Figma design:
- [Whole page](https://www.figma.com/design/zZlFr8tYiRyp4I26sh6eqp/Kiesraad---Abacus-optelsoftware?node-id=141-7306&t=gds6ISdAjOXtzXHE-4)
- ["Stembureau zoeken" states](https://www.figma.com/design/zZlFr8tYiRyp4I26sh6eqp/Kiesraad---Abacus-optelsoftware?node-id=137-5073&t=gds6ISdAjOXtzXHE-4)

# Issues for this epic

- [x] #336 
- [x] #241
- [x] #242
- [x] #243

**Comment by jschuurk-kr** [comment]
@cikzh In our July retro we decided to have two owners per epic. Who is your co-owner for this one?

**Comment by Lionqueen94** [comment]
Does #388 need to be added to this epic or is the epic done?

**Comment by cikzh** [comment]
#388 can only be partially implemented at the moment as scenario 2 has a dependency on Epic #137. We could split the issue and only implement Scenario 1 is this epic. Let's discuss it during standup

**Comment by praseodym** [comment]
Because #388 mentions assigning a data entry to a specific user, it also has a dependency on another future epic, not just #137. I think we should only do #388 when those dependencies are implemented, so not as part of this epic.
