### ISSUE TITLE
Frontend: update data entry navigation

### ISSUE THREAD

**Issue by Lionqueen94** [kiesraad/abacus#133]
See https://github.com/kiesraad/abacus/issues/50#issuecomment-2210730723 for behaviour of navigating between different parts of the data entry and https://github.com/kiesraad/abacus/issues/50#issuecomment-2210833946 for the design links. Also see ["Meerdere fouten en waarschuwingen in 1 response"](https://github.com/kiesraad/abacus-internal/blob/main/use-cases/GSB-validatieregels-plausibiliteitschecks.md#meerdere-fouten-en-waarschuwingen-in-1-response).

Routes changes will be made in #184

**Comment by jschuurk-kr** [comment]
Suggestion no.2 change
`<Route path=":electionId/input" element={<InputLayout />}>`
to
`<Route path="elections/:electionId/input" element={<InputLayout />}>`
