### ISSUE TITLE
Frontend: implement validation copy using unique codes

### ISSUE THREAD

**Issue by praseodym** [kiesraad/abacus#136]
_depends on #135_

Implement [all error/warning copy](https://github.com/kiesraad/opstartfase-team-URN/blob/main/use-cases/GSB-validatieregels-plausibiliteitschecks.md) in frontend. Unique codes are returned by backend when #135 is done.

Tests should also cover the error/warning icons shown in the input fields relevant to the errors/warnings.

**Comment by jschuurk-kr** [comment]
@jorisleker Can you please check the [error/warning copy](https://github.com/kiesraad/opstartfase-team-URN/blob/main/use-cases/GSB-validatieregels-plausibiliteitschecks.md)? With some of the errors for differences changed into warnings, the copy of those probably needs some changes to be less like a blocking error.
