### ISSUE TITLE
Epic: resume data entry

### ISSUE THREAD

**Issue by praseodym** [kiesraad/abacus#137]
- Resume data entry without state
  - Minimal implementation 
- Save data entry form progress to backend so that user can resume where they left off
  - What is currently not saved? Current page, furthest page, pages with accept warnings checkbox checked, ...?
  - ~~Frontend: split up FormState into separate objects for user data, validation results and static data~~ This is too complicated, it makes more sense to write functions to save/restore only user data to/from the backend.
- Load previously saved data entry after partial save
  - Create backend API endpoint to GET saved data
  - Load data in frontend
- Expand Mock Service Worker with persistence to make data entry save/resume work
  - https://github.com/mswjs/data?
- Show unfinalized data entries for the current user on the select polling station page ([Figma](https://www.figma.com/design/zZlFr8tYiRyp4I26sh6eqp/Kiesraad---Abacus-optelsoftware?node-id=4984-25327&node-type=frame&t=xmRE9rXVKD2bdNY2-11))
- Update dom-to-database tests to use new GET API
  - See TODOs in `frontend/e2e-tests/dom-to-db-tests/abort-data-entry.e2e.ts`
- 'Claim' the data entry as soon as 'Beginnen' is clicked, not only when the 'Recounted'-page is saved.
- Update use cases for resume data entry functionality
- ~~Maybe: Avoiding conflicting saves from multiple clients e.g. by working with timestamp or counter: frontend sends timestamp of previous save to backend, backend cancels save when timestamp is older than current save in database, which means that backend was updated by other client and this client state is out of date~~
  - ~~See [Timestamp-based concurrency control](https://en.wikipedia.org/wiki/Timestamp-based_concurrency_control)~~
  - #412, no longer part of this epic.

**Comment by jorisleker** [comment]
@praseodym:

Is showing unfinalized data entries for the current user on the select polling station page part of this epic ([see Figma](https://www.figma.com/design/zZlFr8tYiRyp4I26sh6eqp/Kiesraad---Abacus-optelsoftware?node-id=4984-25327&node-type=frame&t=xmRE9rXVKD2bdNY2-11)).

And regarding the latter, when do we consider a data entry to be associated to a user? I would say after they click 'beginnen' on the select polling station page. Right now, it's only linked to a user after the submit their first data (click 'volgende' on the recounted page). I think that's too late.

**Comment by jorisleker** [comment]
> Maybe: Avoiding conflicting saves from multiple clients e.g. by working with timestamp: frontend sends timestamp of previous save to backend, backend cancels save when timestamp is older than current save in database, which means that backend was updated by other client and this client state is out of date.

Should we prevent accepting posts from multiple users? The user that started the data entry should is the only one allowed to update it? Doesn't really solve the 'multiple clients' issue, unless we prevent users from logging in on multiple devices (which sounds like a smart idea).

**Comment by jschuurk-kr** [comment]
@praseodym In our July retro we decided to have two owners per epic. Who is your co-owner for this one?

**Comment by praseodym** [comment]
I removed #412 from this epic, it's not a priority for this epic so we can pick this up later.

**Comment by jorisleker** [comment]
Can you add a bit more description to #412 so others can also understand what this ticket should implement?

**Comment by praseodym** [comment]
> Can you add a bit more description to [#412](https://github.com/kiesraad/abacus/issues/412) so others can also understand what this ticket should implement?

Done, thanks!
