### ISSUE TITLE
Implement validation rule F.204 (was F.14)

### ISSUE THREAD

**Issue by jschuurk-kr** [kiesraad/abacus#149]
Implement the validation rule F.204 ([F.204: stemmen op kandidaten = som van uitgebrachte stemmen op de lijsten](https://github.com/kiesraad/abacus-internal/blob/main/use-cases/GSB-validatieregels-plausibiliteitschecks.md#f204-stemmen-op-kandidaten--som-van-uitgebrachte-stemmen-op-de-lijsten)) in frontend.

### TODO:
- [x] Implement auto redirect to `Aantal kiezers en stemmen` page showing the error
- [x] Add a test for this

**Comment by Lionqueen94** [comment]
@jschuurk-kr This is done in #166 F.14 is added to the frontend mock api. Is anything else needed for this issue?

**Comment by jschuurk-kr** [comment]
@Lionqueen94 On what page should error F.14 be shown? I can't get the error to appear when running the frontend with the mock.

Also, we need a test for this error. We have a test for every error and warning. They are rather basic for now, but should be extended once we have the copy of the error messages. Then we should assert on the copy and on the error/warning icons in the input fields.

**Comment by Lionqueen94** [comment]
@jorisleker If I'm correct the error F.14 should show up on the `Controleren en opslaan` page right? Or should there be an auto-redirect to the `Aantal kiezers en stemmen` page showing this error?

**Comment by jorisleker** [comment]
@Lionqueen94 auto-redirect.
