### ISSUE TITLE
Frontend: application behavior when a non-existing election ID is used

### ISSUE THREAD

**Issue by cikzh** [kiesraad/abacus#179]
As discussed here: https://github.com/kiesraad/abacus/pull/146#discussion_r1686014231 a user might end up using a non-existing election ID, for example by providing a wrong ID via the URL. This can happen in multiple places in the application, but `/{id}/input` might be an obvious place to test this.

- What should the behavior be when the `election` doesn't exist?
- Determine how to implement this
- Determine how to test this

**Comment by praseodym** [comment]
404 page?

**Comment by praseodym** [comment]
@jorisleker might have a good answer to this :)

**Comment by jorisleker** [comment]
404 page with a text like this?

> Er ging iet mis. De link die je hebt gebruikt is niet (meer) geldig. Ga naar het [overzicht met verkiezingen](#link).
