### ISSUE TITLE
Implement plausibility check W.205 (was W.25)

### ISSUE THREAD

**Issue by Lionqueen94** [kiesraad/abacus#185]
Implement plausibility check W.205 ([W.205 Totaal aantal uitgebrachte stemmen niet leeg en groter dan 0](https://github.com/kiesraad/abacus-internal/blob/main/use-cases/GSB-validatieregels-plausibiliteitschecks.md#w205-totaal-aantal-uitgebrachte-stemmen-niet-leeg-en-groter-dan-0)) in frontend and backend.

**Comment by jschuurk-kr** [comment]
Seems a duplicate with #150. We should do another check if we have covered all errors in warnings in frontend and backend when we get to this issue.
