### ISSUE TITLE
Provide feedback when user clicks "Beginnen" without inputting a (valid) polling station number

### ISSUE THREAD

**Issue by jschuurk-kr** [kiesraad/abacus#195]
On the `1/input` page:

- show the alert "Voer een geldig nummer van een stembureau in om te beginnen" in this [design](https://www.figma.com/design/zZlFr8tYiRyp4I26sh6eqp/Kiesraad---Abacus-optelsoftware?node-id=3663-15455&t=nFxASayzDUpV6xHl-11) when
  - The user does not input a polling station number and clicks "Beginnen"
  - The user inputs a non existing polling station number and clicks "Beginnen"
- Hide the alert when the users edits the polling station number input (i.e. the moment the 'aan het zoeken' message is shown.

The design of the alert component is based on the existing alert that is used in several places, ie after a successful login

**Comment by jorisleker** [comment]
We will also add feedback when the user clicks 'Beginnen' after entering a non-existing polling station number
