### ISSUE TITLE
Improve polling station selection for fast users

### ISSUE THREAD

**Issue by jschuurk-kr** [kiesraad/abacus#234]
## issue description
Steps:
1. Go to the polling station selection screen
2. Enter a valid polling station number
3. While "aan het zoeken..." is being displayed, click "Beginnen"

Result:
- Error is shown "Voer een geldig nummer van een stembureau in om te beginnen"
- As soon as the polling station is found, its name is shown in a green bar next to the input field.
- User remains on the polling station selection screen

![image](https://github.com/user-attachments/assets/d739f1b8-ac8b-464c-97b0-b8f90bfd1a95)

At this point, my first reaction was to click the green bar to get to the first data entry screen. That does not work. Only later did I realize that clicking "Beginnen" would get me to the data entry page.

## summary of discussion in Mattermost
- disabling the "Beginnen" button during the search is not an option because accessibility
- the 500ms debounce is rather slow compared to the previous 200ms
- an option is to remove the error after the debounce, although that would still require the user to click "Beginnen" twice

**Comment by jorisleker** [comment]
The 500ms delay is artificial, and mainly meant to prevent 'not found' messages whilst the user is typing. 

So let's distinguish two things:
- the frontend 'knowing' the result of the user's query (valid / not valid)
- the UI being updated with the result of the user's query (after 500ms debounce)

We can distinguish the following cases when the user clicks the beginnen button:

1. frontend knows result is invalid, UI is updated
2. frontend knows result is invalid, has not updated UI yet
3. frontend knows result is valid, has not updated UI yet
4. frontend knows result is valid, UI is updated
5. frontend does not know the result of the query yet

- Case 2 en 3 should be handled the same way: redirect user to `input/:polling_station_number`
- Case 4 and 5 should be handled the same way: show 'not found' message in UI and 'enter valid number' alert above button. It's okay to update the UI immediately (don't wait the full 500ms before showing the 'not found' message.
- In case 1, i would recommend waiting for the backend response, and handling the users click after that. So if the polling station number was valid, redirect to `input/:polling_station_number`, if the number was invalid, handle it similar to case 4 and 5.

**Comment by lkleuver** [comment]
We could also delay the "not found" but show results instantly.

**Comment by jorisleker** [comment]
would still make the UI a bit 'jumpy' when entering polling station number 123 ('searching', 'found 1', 'searching', 'found 12', 'searching', 'found 123'. The debounce makes this 'searching', 'found 123' in most cases

**Comment by lkleuver** [comment]
Is there a specific reason to step away from "normal" autocomplete behavior showing all results matching the search term instead of one at a time?

**Comment by jorisleker** [comment]
it's not an autocomplete. We want users to enter the full number of the polling station they are going to enter data for, and not have them select one from a list. It's just a couple of keystrokes, and we want to prevent errors when selecting one of the matches from a list.
