### ISSUE TITLE
Use React `ref` instead of `getElementById`

### ISSUE THREAD

**Issue by praseodym** [kiesraad/abacus#290]
Use React `ref` instead of `getElementById` in the frontend codebase, specifically the checkbox references in the form components.

_Originally posted by @praseodym in https://github.com/kiesraad/abacus/pull/233#discussion_r1735682023_

**Comment by lkleuver** [comment]
Is there a specific reason for this?
With the new form component I prefer not to use forwardRef (and mergerefs) and want to refactor soonish to semi controlled inputs.

**Comment by praseodym** [comment]
This issue was created because of the [conversation in #233](https://github.com/kiesraad/abacus/pull/233#discussion_r1735682023) where we decided to pick this up later. We shouldn't be using `getElementById` where we can use a direct `ref` instead.

If we want to refactor the form structure so that we get rid of `getElementById` in another way that's also fine.

**Comment by lkleuver** [comment]
Currently I'm thinking of moving "draft values" to a ref in the form controller.
this means we need to listen for onChange on inputs to update the ref.
so instead of getValues the values will come from draft `{...savedValues, ...pickFromDraftValues}`

Eventually might even move all logic outside the react code into a model/class.

**Comment by praseodym** [comment]
That's a good idea, but also a bigger refactoring than what I had in mind for this issue. I'd suggest that we still do the refactoring that is describe in this issue, and create a new issue for the refactoring that you propose.

Can you create a new issue for the refactoring you're proposing?
