### ISSUE TITLE
Missing focus state in form section navigation

### ISSUE THREAD

**Issue by jorisleker** [kiesraad/abacus#298]
The items in the section menu in data entry forms lack a focus state. 
This has been added to design. See [Figma](https://www.figma.com/design/zZlFr8tYiRyp4I26sh6eqp/Kiesraad---Abacus-optelsoftware?node-id=123-2660&node-type=FRAME&t=lzcBvjqXEZ7UVHM0-11).

### Acceptance criteria
- [x] Focus can only be set on items that the user can navigate to (so it should not be possible to tab to items that are disabled or active)
- [x] When an item has both focus and hover, the focus state overrides the hover

![image](https://github.com/user-attachments/assets/146bf064-9581-4b45-86c9-3c36ee7c54bc)

**Comment by jorisleker** [comment]
@Lionqueen94 noticed another missing focus state: the 'accept warnings' checkbox does not have any. Could you add that as well as part of this ticket? You could use the glow effect we also use on `input type="button"`

**Comment by jorisleker** [comment]
Also: updated design of the focus state of menu-items: inset border instead of outset, so it does not overlap with adjacent items.

**Comment by Lionqueen94** [comment]
@jorisleker I have implemented all your suggestions in #357 
I'm still missing a hover state for the checkbox, can you add this to the design/let me know in a reply what that should look like?

**Comment by jorisleker** [comment]
@Lionqueen94 I think something went wrong / I wasn't clear in my description. 

- The focus state for buttons (outer glow) did not need changing. I see you implemented the border style that was intended for the progresslists on them.
- Focus state for checkboxes should be the same outer glow buttons used to have.
- I don't see the focus state for items in the progress list (see screeshot), they just get a funny 1px border-top, but that should be a 2px inset border
- Also: I see I can focus items in the progress list that are beyond the furthest item. I think those should have a `taborder="-1"` so tabbing skips over them

Screenshot: funny focus-state on progress list items:
<img width="365" alt="Scherm­afbeelding 2024-09-22 om 11 41 29" src="https://github.com/user-attachments/assets/1c316417-83fc-4aa8-a2c0-09fdc5a502ff">

Screenshot: focus state of buttons that should be reverted:
<img width="503" alt="Scherm­afbeelding 2024-09-22 om 11 43 02" src="https://github.com/user-attachments/assets/35807cce-8817-46d6-b844-58b1444f912a">
