### ISSUE TITLE
Expand tests for PDF generation and result summation

### ISSUE THREAD

**Issue by praseodym** [kiesraad/abacus#335]
> > The tests right now are relatively barebones, but at least we test some successful additions. I would suggest to at add much more significant testing as an issue for a later time (soonish)
> 
> Fine with me to do it in a later issue, as long as that issue is part of the same epic as this PR/issue.

_Originally posted by @jschuurk-kr in https://github.com/kiesraad/abacus/issues/324#issuecomment-2342993720_
            
# TODO

- Expand d2d test with PDF generation
- Expand unit tests
  - using the *"0, 1, many, lots, oops"* heuristic (*many*: more than one; *lots*: very very many; *oops*: errors), can be applied both to the counts, as to the number of polling stations
  - Cover the case @ring-ring-ring  ran into during a demo: `"dictionary does not contain key \"house_number_addition\""`

**Comment by jschuurk-kr** [comment]
@rnijveld This issue has been closed with the merge of [PR 485](https://github.com/kiesraad/abacus/pull/485), but the issue also mentions adding a dom-to-database test for the downloading of the report. Is that still coming on a separate PR?
