### ISSUE TITLE
Update data entry navigation design for long list of parties

### ISSUE THREAD

**Issue by praseodym** [kiesraad/abacus#338]
In the election for House of Representatives (Tweede Kamer), sometimes more than 30 parties participate. This does not fit well into the navigation structure we currently have for the input screens. Therefore, we will adjust the navigation menu as follows:

- The items before the lists are fixed at the top of the navigation column.
- The item 'check and save' is fixed at the bottom of the navigation column.
- The section with lists is scrollable.
- After each navigation action (via 'next' or via the navigation menu), we ensure that the active step is visible (`scrollIntoView`).
- As long as the list is not completely scrolled to the top (`scrollPosition > Scrolltop`), we show a fadeout at the top of the list.
- As long as the list is not completely scrolled to the bottom (`scrollPosition + height < scrollBottom`), we show a fadeout at the bottom of the list.

[Design in Figma](https://www.figma.com/design/zZlFr8tYiRyp4I26sh6eqp/Kiesraad---Abacus-optelsoftware?node-id=4927-36061&node-type=SECTION&t=yrnZQIcxc8CMyLZF-11)

**Comment by jorisleker** [comment]
This is also relevant for municipal elections, mainly in bigger municipalities:

Number of parties participating in G4 municipal elections 2022

| Municipality      | Number of parties |
|---------------|------|
| **Amsterdam**  | 26   |
| **Rotterdam**  | 20   |
| **Den Haag**  | 20   |
| **Utrecht**  | 19   |
