### ISSUE TITLE
Speed up dom-to-database tests

### ISSUE THREAD

**Issue by praseodym** [kiesraad/abacus#363]
Due to the fixture to reset the backend between every run (#327), our tests got a lot slower. We can work around this by sharding our tests. We could choose to shard by browser, or use the [integrated Playwright sharding functionality](https://playwright.dev/docs/test-sharding).

We can shard by using multiple GitHub Actions runners (e.g. [using a matrix strategy](https://timdeschryver.dev/blog/using-playwright-test-shards-in-combination-with-a-job-matrix-to-improve-your-ci-speed#github-workflow-matrix)) or maybe even by running multiple shards in a single runner (but with different API endpoints).

Playwright lets you install a specific browser, .e.g `npx playwright install webkit`, so we could choose to cache only the node modules, and let each browser-specific runner install the browser they need.

The best way to experiment with GitHub Actions is to fork the repository first, and then try out changes in the forked repository.

**Comment by jschuurk-kr** [comment]
Working on it in this fork: https://github.com/jschuurk-kr/abacus/blob/main/.github/workflows/build-lint-test.yml
