### ISSUE TITLE
Provide complete build as GitHub Actions artifact

### ISSUE THREAD

**Issue by praseodym** [kiesraad/abacus#366]
Once #365 is done, we should provide builds of the Abacus server (backend+frontend) built using GitHub Actions. This build can be made available for download by [uploading it as an artifact](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts).

The best way to experiment with GitHub Actions is to fork the repository first, and then try out changes in the forked repository.

**Comment by cikzh** [comment]
Implemented in #447 

You can download and run the backend-build artifact from GitHub actions. Run with the `-rs ` flags to get a fresh database (will be stored on disk alongside the binary)
