### ISSUE TITLE
Show unfinalised data entries on polling station choice page

### ISSUE THREAD

**Issue by praseodym** [kiesraad/abacus#369]
Show unfinalized data entries for the current user on the select polling station page ([Figma](https://www.figma.com/design/zZlFr8tYiRyp4I26sh6eqp/Kiesraad---Abacus-optelsoftware?node-id=4984-25327&node-type=frame&t=xmRE9rXVKD2bdNY2-11)). This also implies expanding the backend `PollingStationStatus` with an "in progress" state (`first_entry_in_progress`??).

**Comment by Lionqueen94** [comment]
Do you also want to add a `second_entry_in_progress` once we implement the second entry flow? Or can we determine in progress based on something else and have a generic `in_progress` state?

**Comment by praseodym** [comment]
> Do you also want to add a `second_entry_in_progress` once we implement the second entry flow? Or can we determine in progress based on something else and have a generic `in_progress` state?

Yes, once we implement the second data entry.
