### ISSUE TITLE
Feedback when polling station in progress or completed

### ISSUE THREAD

**Issue by jorisleker** [kiesraad/abacus#388]
When searching for a polling station, you can run into a couple of scenario's that we don't have proper feedback for yet.

1. Polling station is found, but already finalized (first + second input complete, regardless whether there a differences, etc):
![image](https://github.com/user-attachments/assets/5734977e-9413-40ab-a310-444dec6f0f85)

2. Polling station is found, but assigned to another user (regardless whether it's first or second data entry):
![image](https://github.com/user-attachments/assets/4fb2b23d-aa54-49c2-b48d-c97c1f07ba43)

3. Polling station is found, has entry data and is assigned to current user (status batch for first and second entry has pencil icon): 
![image](https://github.com/user-attachments/assets/48fd55b7-4d41-42a3-ba7e-ca04126f33ed)

In scenario 1 and 2, if the user clicks the submit button, we show the feedback that is already implemented, no need to change.

The design of the 'search by polling station number' component can be found [on the components page in Figma](https://www.figma.com/design/zZlFr8tYiRyp4I26sh6eqp/Kiesraad---Abacus-optelsoftware?node-id=137-5073&t=fwYzqCKFITZhwsl2-4)

**Note**: Right now we have not implemented users/roles yet. That means scenario 2 can't be addressed yet. Please create a new ticket to implement that behavior after users and roles have been implemented.

**Comment by Lionqueen94** [comment]
Added new issue #704 and implemented scenario 1 in https://github.com/kiesraad/abacus/pull/703
