### ISSUE TITLE
Make sure we never show autocomplete on inputs

### ISSUE THREAD

**Issue by jorisleker** [kiesraad/abacus#394]
On the laptops we use for demo-ing (ubuntu/firefox), browsers are in their default config, which means autocomplete for input's is switched on. 

We should make sure we never show autocomplete/auto populate on the inputs in our application. 
https://www.w3schools.com/howto/howto_html_autocomplete_off.asp

**Comment by lkleuver** [comment]
For what do we want to disable autocomplete? 
NumberInput is obvious but also others? like polling station search?

**Comment by jorisleker** [comment]
> For what do we want to disable autocomplete?
> NumberInput is obvious but also others? like polling station search?

I think we should add this to all inputs(including, but not limited to, both cases you mentioned) and textareas
