### ISSUE TITLE
Epic: user roles

### ISSUE THREAD

**Issue by praseodym** [kiesraad/abacus#397]
Add scaffolding in the frontend to provide pages for different user roles: administrator (beheerder), coordinator and data entry (invoerder).

- Update navbar with role
- Remove PDF creation from data entry role, move it to coordinator
- Determine frontend URLs for roles

See the [use case 'autorisatiematrix'](https://github.com/kiesraad/abacus/blob/main/documentatie/use-cases/autorisatiematrix.md) for details on the three roles.

Suggestion for the URL paths:
- `/elections` 
  - administrator role: configure elections
  - data entry role: election list
- `/elections/{election_id}` 
  - coordinator role: election session start/stop/pause
- `/elections/{election_id}/report` 
  - coordinator role: create report (proces-verbaal)
- `/elections/{election_id}/polling-stations` 
  - administrator+coordinator roles: configure polling stations
- `/elections/{election_id}/polling-stations/1` 
  - administrator+coordinator roles: configure polling station 1
- `/elections/{election_id}/status` 
  - coordinator role: data entry status
- `/elections/{election_id}/data-entry` 
  - data entry role: data entry polling station choice
- `/elections/{election_id}/data-entry/{polling_station_id}` 
  - data entry form
- `/users` 
  - administrator+coordinator roles: configure users
- `/workstations` 
  - administrator role: configure workstations
- `/logs` 
  - administrator+coordinator roles: view logs

Edited URLs with underscores to dashes as this is best practice Joris told us before, see https://developers.google.com/search/docs/crawling-indexing/url-structure

**Comment by praseodym** [comment]
With regard to the URL paths: the administrator has the ability to configure new elections, so the URL path should be independent of the election. Maybe we should go for `/administration/...`, `/data-entry/...` and `/coordination/...` instead?

**Comment by Lionqueen94** [comment]
> With regard to the URL paths: the administrator has the ability to configure new elections, so the URL path should be independent of the election. Maybe we should go for `/administration/...`, `/data-entry/...` and `/coordination/...` instead?

So changing the current data-entry paths as well? So `/data-entry/elections/{election_id}/polling_station/{polling_station_id}/`? Otherwise we will have election id and polling station id next to eachother
