### ISSUE TITLE
Choose i18n library

### ISSUE THREAD

**Issue by praseodym** [kiesraad/abacus#409]
From #45: which i18n library do we want to use? Options: [i18next](https://www.i18next.com) / [react-i18next](https://www.npmjs.com/package/react-i18next) / [formatjs](https://formatjs.io/) / ...?.

**Comment by lkleuver** [comment]
# Choosing an i18n library

## Constraints
- Must work well with React
- Well supported translations format

## Contenders

### FormatJS
Website: [FormatJS.io](https://formatjs.io/)
React library: [react-intl](https://formatjs.io/docs/react-intl/)
Last commit: 4 days ago

> FormatJS is a modular collection of JavaScript libraries for internationalization that are focused on formatting numbers, dates, and strings for displaying to people. It includes a set of core libraries that build on the JavaScript Intl built-ins and industry-wide i18n standards, plus a set of integrations for common template and component libraries.   


Example usage in React
```jsx
  <h2>
    <FormattedMessage id="app.welcome" />
  </h2>
```

#### Bundling
Implement youreelf

#### Translation extraction 
Babel plugin

### i18Next
Website: [i18next.com](https://i18next.com)
React library: [react-i18next](https://react.i18next.com/)
Last commit: 3 days ago

> i18next is an internationalization-framework written in and for JavaScript. But it's much more than that!

> i18next goes beyond just providing the standard i18n features such as (plurals, context, interpolation, format). It provides you with a complete solution to localize your product from web to mobile and desktop.  


Example usage in React
```jsx
<h2>{t('Hello Abacus')}</h2>
```

#### Bundling
Multiple plugins for bundling or loading multiple locations

#### Translation extraction
- Save missing features
- Code parsers (3rd party)


## Conclusion
Both frameworks fit the constrainst. FormatJs has a nice feature that it uses the browser builtin functionality to provide formatting (with optional polyfill)

Both have an active community and repository. 
But i18next seems to be the marginal winner in most categories.

i!8next has a more mature ecosystem and it has more flexibility to fit our needs.

**Comment by lkleuver** [comment]
We are currently exploring implementing our own i18n library, making it more lean, easier to maintain and less security risks.
A concept can be found in this PR:
https://github.com/kiesraad/abacus/pull/459

**Comment by marlonbaeten** [comment]
For now we use vanilla TS translate functions. We explicitly designed these to match the translation calls in popular frameworks like i18next. From a security approach not adding an additional dependency makes sense.
