### ISSUE TITLE
Save cached input after clicking save in modal

### ISSUE THREAD

**Issue by praseodym** [kiesraad/abacus#421]
> Regarding "- If the furthest page was edited and not explicitly saved, these changes are lost. Is this ok?"
> To me it makes sense if you navigate away from the form that the cached input is sent to the backend to be saved. Since you explicitly click `Invoer bewaren` (even if you are not on that specific page). @jorisleker what do you think?

_Originally posted by @Lionqueen94 in https://github.com/kiesraad/abacus/issues/417#issuecomment-2391838912_

> Agree with @Lionqueen94. Input on furthest page should be saved if you choose invoer bewaren.

_Originally posted by @jorisleker in https://github.com/kiesraad/abacus/issues/417#issuecomment-2392146990_

The flow is described in the [data entry flowchart](https://github.com/kiesraad/abacus/blob/main/documentatie/flowcharts/data-entry-forms.md). This covers the 'cached data' (input on the furthest page that was not yet saved by clicking next, while the user navigated to a different form page in the meantime), but not whether this data should be saved when navigating away or aborting the data entry using the button.

Let's figure out what behaviour we should have, clarify in our documentation (the flowchart) and implement any changes in the code if needed.

**Comment by jorisleker** [comment]
@praseodym When testing #417, I noticed that the cached data is already saved to the backend when using 'invoer afbreken'. From @Lionqueen94's comment I understood that this isn't always the case, but could not reproduce this.

**Comment by praseodym** [comment]
> [@praseodym](https://github.com/praseodym) When testing [#417](https://github.com/kiesraad/abacus/pull/417), I noticed that the cached data is already saved to the backend when using 'invoer afbreken'. From [@Lionqueen94](https://github.com/Lionqueen94)'s comment I understood that this isn't always the case, but could not reproduce this.

I think it is saved when you click 'invoer afbreken' from the page with cached data, but not from other pages. Can you confirm this?

**Comment by jorisleker** [comment]
> > [@praseodym](https://github.com/praseodym) When testing [#417](https://github.com/kiesraad/abacus/pull/417), I noticed that the cached data is already saved to the backend when using 'invoer afbreken'. From [@Lionqueen94](https://github.com/Lionqueen94)'s comment I understood that this isn't always the case, but could not reproduce this.
> 
> I think it is saved when you click 'invoer afbreken' from the page with cached data, but not from other pages. Can you confirm this?

Confirmed!

**Comment by jorisleker** [comment]
Testing this I noticed another bug in #417, see [comment, part 2](https://github.com/kiesraad/abacus/pull/417#pullrequestreview-2347886699)
