### ISSUE TITLE
Create UI Table component

### ISSUE THREAD

**Issue by oliver3** [kiesraad/abacus#433]
- [x] Create basic table component - https://github.com/kiesraad/abacus/pull/521
- [x] Use component instead of html tables throughout the application - https://github.com/kiesraad/abacus/pull/563

#542 and #506 will be implemented at a later stage

Notes:
- Number columns have proper spacing between integers (e.g. polling station numbers, see [this comment](https://github.com/kiesraad/abacus/pull/453#discussion_r1804763599))

**Comment by jorisleker** [comment]
re: Number columns have proper spacing between integers

We should only do this for number columns where comparing/adding numbers is expected. Ie: columns with counts or other statistics. In situations where the presented number is an **identifier** (ie polling station number, candidate number, list number), I prefer using the default font + 'normal' letterspacing that is optimized for legibility.
