### ISSUE TITLE
Flaky navigation panel icons test

### ISSUE THREAD

**Issue by praseodym** [kiesraad/abacus#436]
This test repeatedly fails in CI at this specific line:
```
  1) [firefox] › data-entry.e2e.ts:673:5 › navigation › navigation panel icons › check icons for accept, active, empty, error, warning, unsaved statuses 

    Error: locator.check: Clicking the checkbox did not change its state
    Call log:
      - waiting for getByLabel('Ik heb de aantallen gecontroleerd met het papier en correct overgenomen.')
      -   locator resolved to <input type="checkbox" id="voters_and_votes_form_accept_warnings" name="voters_and_votes_form_accept_warnings"/>
      - attempting click action
      -   scrolling into view if needed
      -   done scrolling
      -   forcing action
      -   performing click action
      -   click action done
      -   waiting for scheduled navigations to finish
      -   navigations have finished


       at ../page-objects/data_entry/VotersAndVotesPgObj.ts:113

      111 |     await this.acceptWarnings.waitFor();
      112 |     // eslint-disable-next-line playwright/no-force-option -- force option needed to click on hidden element
    > 113 |     await this.acceptWarnings.check({ force: true, noWaitAfter: true });
          |                               ^
      114 |   }
      115 | }
      116 |

        at VotersAndVotesPage.checkAcceptWarnings (/home/runner/work/abacus/abacus/frontend/e2e-tests/page-objects/data_entry/VotersAndVotesPgObj.ts:113:31)
        at /home/runner/work/abacus/abacus/frontend/e2e-tests/dom-to-db-tests/data-entry.e2e.ts:699:7
```
Let's figure out if there is something we can do to improve the success rate (or if there's an actual bug, like a race condition, in the frontend itself).

**Comment by jschuurk-kr** [comment]
@praseodym Is it only this particular test (dom-to-db test for navigation icons) that's flaky?

Because it's not a 'proper' dom-to-db test (as in: covers part of a use case) and we now also test the nav icons in "Progress list shows correct icons" in `PollingStation.test.tsx`. Not that it's not worth investigating at all, but I don't think we should spend too much time on it, if it's only for a test that arguably can be deleted.

**Comment by Lionqueen94** [comment]
> [@Lionqueen94](https://github.com/Lionqueen94) and I concluded that all tests that use `acceptWarnings` are flaky.
> 
> [#435](https://github.com/kiesraad/abacus/pull/435) might have improved this situation already.

I have not gotten a flaky acceptWarnings test since it was merged. Since the use the default radio and checkbox inputs I think it is a lot better now.

**Comment by praseodym** [comment]
Then I suggest we close this issue and reopen if it happens again.
