### ISSUE TITLE
Add election status to the header of the Election Status page

### ISSUE THREAD

**Issue by Lionqueen94** [kiesraad/abacus#464]
Figma design: https://www.figma.com/design/zZlFr8tYiRyp4I26sh6eqp/Kiesraad---Abacus-optelsoftware?node-id=4922-44704&node-type=instance&m=dev

Add election statuses to backend.
Show statuses on election list page as well.

Statuses for now:
- [x] `Steminvoer bezig` (coordinator) / `Invoer gestart` (typist)
- [x] `Steminvoer afronden` (only frontend on report page)
- [x] `Steminvoer afgerond` (coordinator) / `Steminvoer voltooid` (typist)

Do not include `Klaar voor invoer`, `Invoerfase starten` and `Invoer geschorst` (coordinator) / `Invoer opgeschort` (typist) for now.

**Comment by Lionqueen94** [comment]
@jorisleker Are there different election statuses for administrators vs typists? I see differences between the statuses on https://www.figma.com/design/zZlFr8tYiRyp4I26sh6eqp/Kiesraad---Abacus-optelsoftware?node-id=1077-35635&node-type=frame&m=dev and https://www.figma.com/design/zZlFr8tYiRyp4I26sh6eqp/Kiesraad---Abacus-optelsoftware?node-id=1077-30631&node-type=frame&m=dev

**Comment by jorisleker** [comment]
No the statussen themselves don't differ, but the labels do. I think the mapping is quite obvious, if not, let me know and I will clarify.

**Comment by Lionqueen94** [comment]
> No the statussen themselves don't differ, but the labels do. I think the mapping is quite obvious, if not, let me know and I will clarify.

I see `Wachten op coordinator` as a status for the typist role, what status does this map to for the coordinator? The other ones I've mapped in the description, please let me know if there is anything wrong there.
