### ISSUE TITLE
Escalate some errors in `PollingStationFormController.tsx` 

### ISSUE THREAD

**Issue by marlonbaeten** [kiesraad/abacus#473]

**Comment by praseodym** [comment]
I noticed in #566 when the API request after clicking the 'Invoer opslaan' button in the 'Invoer afbreken' modal returns an error (e.g. status code 422), no error is shown to the user. I think that should be in scope to be fixed with this issue.

**Comment by marlonbaeten** [comment]
> I noticed in [#566](https://github.com/kiesraad/abacus/pull/566) when the API request after clicking the 'Invoer opslaan' button in the 'Invoer afbreken' modal returns an error (e.g. status code 422), no error is shown to the user. I think that should be in scope to be fixed with this issue.

I think this is resolved with: https://github.com/kiesraad/abacus/pull/577/commits/4a7da4bafba5896a18f6bb6398462e1e30766aa9
