### ISSUE TITLE
Do not send all fields in endpoints

### ISSUE THREAD

**Issue by oliver3** [kiesraad/abacus#482]
Some endpoints, (e.g. get polling stations, election details), return a list of object with all their fields, even though not all fields are shown on the page. We can optimize this by only sending the fields that are actually used by the frontend.

**Comment by praseodym** [comment]
If this is purely a performance optimization, I don't think it's worth the maintenance and testing overhead to have separate API endpoints that return fewer fields. Also, Abacus will be used on fast local networks so the network overhead is negligible, and I don't think removing some unused fields from the JSON objects will make a noticeable difference in the performance of our backend and frontend.
