### ISSUE TITLE
Create automated GitHub releases

### ISSUE THREAD

**Issue by praseodym** [kiesraad/abacus#619]
To allow users to easily download a build of Abacus, we want to create automated [GitHub releases](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases) on a regular basis. This should be done after we have builds for other platforms (#362).

**Comment by marlonbaeten** [comment]
- Build abacus in release mode
- Run cargo test
- Run playwright-d2d tests
- Create a github release with binaries for linux, osx, windows
- Trigger job manually and automatically once every week
