### ISSUE TITLE
Unfinalised data entry not shown on polling station choice page

### ISSUE THREAD

**Issue by jorisleker** [kiesraad/abacus#623]
Tested on main (e2ff56f7)

**Reproduction steps**
- start a data entry
- abort the data entry, and choose to save it
- you are redirected to the polling station choice page, which contains a blue box with a link to the unfinished data entry. So far so good.
- open the data entry again
- don't make any changes
- Click on one of the links in the breadcrumb navigation (ie. the election name)
- Expected: the unfinished data entry is shown on polling station choice page (as in 3rd bullet)
- Observed: the polling station choice page does not show your unfinished data entry

**Note**: 
On the election status page (for coordinators) there is difference in how the data entry is shown:
- if it is shown on polling station choice page, it is displayed in the 'invoer afgebroken' table
- If it not shown on the polling station choice page, it is displayed in the 'invoer bezig' table

**What needs to be fixed**:
- For the polling station choice page, the difference between 'aborted' and 'busy' is irrelevant. It should be shown in both cases. 
- When navigating away from a data-entry without changes, the 'do you want to save' dialog is not shown. But the 'aborted' status should be set, as you are no longer working on that data-entry.

**Comment by praseodym** [comment]
Please also fix the `json_extract` nightmare introduced in #481:

              Impressive SQL work here, but architecturally this is a nightmare: we're now using the untyped _client state_ (only meant to let the client resume where it left off!) in the backend by letting SQLite parse JSON for each row.

I think it would be good to reconsider the approach when fixing #623, e.g. by adding a column for this state.

_Originally posted by @praseodym in https://github.com/kiesraad/abacus/pull/481#discussion_r1850822737_

**Comment by oliver3** [comment]
Decided together with @jorisleker to leave the 'aborted' state for what it is, for now, and only fix that data entry with both statuses should show up as 'openstaande invoer' on the polling station choice page.

**Comment by praseodym** [comment]
> Decided together with [@jorisleker](https://github.com/jorisleker) to leave the 'aborted' state for what it is, for now, and only fix that data entry with both statuses should show up as 'openstaande invoer' on the polling station choice page.

If we leave that part as-is, are we still going to find a way not to use the client state in the backend?
