### ISSUE TITLE
Warning when 'aantal kiesgerechtigden' is empty

### ISSUE THREAD

**Issue by oliver3** [kiesraad/abacus#683]
While creating the use case, we found the following requirement:

> Bij het invoeren/beheren van stembureaus toont de applicatie een waarschuwing als het aantal kiesgerechtigden niet is ingevuld. De gebruiker heeft twee opties: (1) aantal kiesgerechtigden invullen, (2) aangeven dat aantal kiesgerechtigden bewust leeg wordt gelaten.

We have to decide how to handle this warning and implement it.

**Comment by jschuurk-kr** [comment]
Discussed in standup 11Dec24: we're dropping this requirement (see above for reasons), so closing this issue.

Removing the requirement from the use cases happens in #639.
