### ISSUE TITLE
Polling station address: Align backend with design

### ISSUE THREAD

**Issue by lkleuver** [kiesraad/abacus#684]
Align fields in the database with EML design and frontend.

- address
- house_number
- house_number_addition

The backend currently still has separate fields that should be condensed into a single field.

**Comment by jorisleker** [comment]
Not wanting to open this discussion again, but my assumption was that the EML_NL standard only had an address line and not separate fields. Also: do we know the format of the polling station files municipalities currently use to import their data into OSV2020? (those files are created by software used by the Burgerzaken department. 

If those files don't have housenumber and housenumber addition in separate fields, we will run into issues importing that data. Please remember that for most municipalities this is the primary way polling stations will be added to Abacus. 

@praseodym your thoughts

**Comment by praseodym** [comment]
> (might just be confused by the description of this issue btw, as it isn't really clear on what needs to happen. If aligning backend with design means consolidating `address`, `house_number` and `house_number_addition` into a single address-field field, then please disregard what I said before).

That's what this issue is about, the backend currently still has separate fields that should be condensed into a single field.
