### ISSUE TITLE
Consider changing frontend data entry URL

### ISSUE THREAD

**Issue by praseodym** [kiesraad/abacus#697]
> I think it's clearer to not have 2 numbers following each other in a URL. Maybe add the word `/entry/` in between? Or change the URL to `/elections/{election_id}/polling_station/{polling_station_id}/data-entry/{entry_number}` for example

_Originally posted by @Lionqueen94 in https://github.com/kiesraad/abacus/pull/658#discussion_r1871503708_

**Comment by praseodym** [comment]
We currently have these paths:
- `/elections/1/polling-stations` list of polling stations for coordinator 
- `/elections/1/polling-stations/create` create new polling station
- `/elections/1/polling-stations/update/1` update polling station 1
- `/elections/1/data-entry/` data entry home page
- `/elections/1/data-entry/1/1` first data entry for polling station 1

I agree that having two numbers next to each other in the path does not look good, but I'm also not sure how to fix it. Something like `/elections/1/polling-stations/1/data-entry/1` could work, but then we'd also have to change the update page path. And then where do we put the data entry home page?

**Comment by Lionqueen94** [comment]
> We currently have these paths:
> 
>     * `/elections/1/polling-stations` list of polling stations for coordinator
> 
>     * `/elections/1/polling-stations/create` create new polling station
> 
>     * `/elections/1/polling-stations/update/1` update polling station 1
> 
>     * `/elections/1/data-entry/` data entry home page
> 
>     * `/elections/1/data-entry/1/1` first data entry for polling station 1
> 
> 
> I agree that having two numbers next to each other in the path does not look good, but I'm also not sure how to fix it. Something like `/elections/1/polling-stations/1/data-entry/1` could work, but then we'd also have to change the update page path. And then where do we put the data entry home page?

I actually thought the update path of polling station needed changing so I did this already here: https://github.com/kiesraad/abacus/pull/701

**Comment by jorisleker** [comment]
I think duplicate usage of '/elections' is a bit confusing. How about putting everything for the coordinator and/or functional manager in a separate root path?

Something like this?

* `/manage/elections/1/polling-stations` list of polling stations for coordinator
* `/manage/elections/1/polling-stations/create` create new polling station
* `/manage/elections/1/polling-stations/update/1` update polling station 1
* `/elections/1/polling-stations` data entry home page
* `/elections/1/polling-stations/1/data-entry/1` first data entry for polling station 1

**Comment by praseodym** [comment]
#652 will change the backend endpoints so that it's no longer needed to explicitly specify which entry number is being worked on. When that's done we no longer need to keep track of the entry number in the frontend paths either, so the original issue of the two subsequent numbers is resolved.

Moving the coordinator/management paths to a new `/manage` or `/admin` root might still be a good idea, though.

**Comment by Lionqueen94** [comment]
> [#652](https://github.com/kiesraad/abacus/issues/652) will change the backend endpoints so that it's no longer needed to explicitly specify which entry number is being worked on. When that's done we no longer need to keep track of the entry number in the frontend paths either, so the original issue of the two subsequent numbers is resolved.
> 
> Moving the coordinator/management paths to a new `/manage` or `/admin` root might still be a good idea, though.

So shall we keep this issue open to change the frontend paths (remove the entry numbers) or change the frontend paths also in #652 ?

**Comment by praseodym** [comment]
I've created #762 as part of #697 and will close this issue.
