### ISSUE TITLE
Make sure tooltip is linked to input field with error and is shown under the input field even when scrolling the page

### ISSUE THREAD

**Issue by Lionqueen94** [kiesraad/abacus#73]
* Link tooltip to error in DOM for accessibility and testing
* Make sure tooltip is positioned correctly after scrolling, window/viewport resizing, zooming
* Make sure only the desired keypresses cause the tooltip to disappear. Currently any keypress makes the tooltip disappear, e.g. when hitting `ctrl` to change the zoom level of the browser using the keyboard.
* Make sure there are no warning or errors in the console. Current implementation throws a "two children with the same key" error and a "Source map error" warning, when pasting twice in the same field.
* Write tests for tooltip rendering and positioning

Reproduction steps:
- scroll the page
- paste 'abc' in an input
- expected: the tooltip is shown below the input
- observed: the tooltip is shown somewhere else 

To discuss: What should the tooltip say when pasting an image or a file? Currently it says "Je probeert te plakken. Je kunt hier alleen cijfers invullen." (example [here](https://github.com/kiesraad/urn-uitslag/pull/68#issuecomment-2175579979)) Would be nice if the tooltip mentions what you're trying to paste, as it does in the other cases.

**Comment by praseodym** [comment]
Closing in favour of #299.
